- name: Converge Clickhouse + Lighthouse
  hosts: fullstack
  gather_facts: true
  vars:
    clickhouse_dbs_default:
      - name: logs
    clickhouse_networks_default:
      - "::/0"
      - "127.0.0.1"
    clickhouse_listen_host_default: ["::"]
    clickhouse_version: "22.3.3.44"
  roles:
    - role: ansible_role_clickhouse
    - role: ansible_role_lighthouse
  post_tasks:
    - name: Extra Config | Gather list of existing tables in logs db
      command: "clickhouse-client -h 127.0.0.1 --port 9000 -q 'use logs; show tables'"
      changed_when: false
      register: existing_tables
    - name: Extra Config | Create table if not exists
      command: |
        clickhouse-client -h 127.0.0.1 --port 9000
        -q 'CREATE TABLE IF NOT EXISTS logs.test (message String) ENGINE = Log()'
      when: "'test' not in existing_databases.stdout_lines"

- name: Converge Vector
  hosts: fullstack
  gather_facts: true
  roles:
    - role: ansible_role_vector
  vars:
    role_vector_endpoint_clickhouse_database: "logs"
    role_vector_endpoint_clickhouse_table: "test"
    role_vector_groups: ["sys"]