- name: Converge Clickhouse + Lighthouse
  hosts: fullstack
  gather_facts: true
  roles:
    - role: ansible_role_clickhouse
    - role: ansible_role_lighthouse
  vars:
    clickhouse_dbs_default:
      - name: logs
    clickhouse_networks_default:
      - "::/0"
      - "127.0.0.1"
    clickhouse_version: "22.3.3.44"
    clickhouse_listen_host_default:
      - "::"
    clickhouse_ready_delay: 1
  post_tasks:
    - name: Config | Create table
      command: |
        clickhouse-client -h 127.0.0.1 --port 9000
        -q 'CREATE TABLE IF NOT EXISTS `{{ role_vector_endpoint_clickhouse_database }}.{{ role_vector_endpoint_clickhouse_table }} (message String) ENGINE=MergeTree()`'

- name: Converge Vector
  hosts: fullstack
  gather_facts: true
  roles:
    - role: ansible_role_vector
  vars:
    role_vector_endpoint_clickhouse_database: "logs"
    role_vector_endpoint_clickhouse_table: "test"
    role_vector_groups: ["sys"]