---
dependency:
  name: galaxy
  options:
    requirements-file: molecule/shared/collections.yml
    role-file: molecule/fullstack/requirements.yml
driver:
  name: docker
lint: |
  set -e
  pwd
  ls -lha
  ansible-lint . --exclude ./.tox/ --exclude ./.git/
platforms:

  - name: fullstack_centos
    groups:
      - fullstack
    image: centos:7
    dockerfile: ../resources/Dockerfile.j2
    privileged: true
    cgroupns_mode: host
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    command: /usr/sbin/init

provisioner:
  name: ansible
  options:
    D: True
verifier:
  name: ansible
