---
roles:
  - name: nginx
    src: https://github.com/nginxinc/ansible-role-nginx.git
    version: "0.24.2"
    scm: git

  - src: https://github.com/AlexeySetevoi/ansible-clickhouse.git
    scm: git
    version: "1.13"
    name: ansible_role_clickhouse

  - src: https://github.com/smutosey/ansible_role_vector.git
    scm: git
    version: "1.0"
    name: ansible_role_vector