---
- name: Verify
  hosts: fullstack
  tasks:
    - name: VERIFY | Gather Local Services
      ansible.builtin.service_facts:
      become: true

    - name: VERIFY | Assert Clickhouse Service
      ansible.builtin.assert:
        that:
          - "clickhouse_service in ansible_facts.services"
          - "'running' == ansible_facts.services[clickhouse_service].state"
          - "'enabled' == ansible_facts.services[clickhouse_service].status"
          - "vector_service in ansible_facts.services"
          - "'running' == ansible_facts.services[vector_service].state"
          - "'enabled' == ansible_facts.services[vector_service].status"
          - "nginx_service in ansible_facts.services"
          - "'running' == ansible_facts.services[nginx_service].state"
          - "'enabled' == ansible_facts.services[nginx_service].status"
      vars:
        clickhouse_service: 'clickhouse-server.service'
        vector_service: 'vector.service'
        nginx_service: 'nginx.service'

    - name: VERIFY | Gather list of existing databases
      ansible.builtin.command: "clickhouse-client -h 127.0.0.1 --port {{ clickhouse_tcp_port }} -q 'show databases'"
      changed_when: false
      register: databases
      vars:
        clickhouse_tcp_port: 9000

    - name: VERIFY | Assert Test Databases
      ansible.builtin.assert:
        that:
          - "'logs' in databases.stdout"

    - name: VERIFY | Check Vector API (GET /health status 200)
      ansible.builtin.uri:
        url: "http://0.0.0.0:{{ role_vector_port }}/health"
      vars:
        role_vector_port: 8686

    - name: VERIFY | Check Lighthouse (GET status 200)
      ansible.builtin.uri:
        url: "http://0.0.0.0:80"

    - name: VERIFY | Sleep for 15 seconds and continue with play
      ansible.builtin.wait_for:
        timeout: 15
      delegate_to: localhost

    - name: VERIFY | Check logs in db
      ansible.builtin.command: "clickhouse-client -h 127.0.0.1 --port 9000 -q 'select * from logs.test'"
      changed_when: false
      register: test_logs

    - name: VERIFY | Output logs in Clickhouse DB received from Vector
      ansible.builtin.debug:
        var: test_logs.stdout_lines

    - name: VERIFY | Assert log lines exists
      ansible.builtin.assert:
        that:
          - "test_logs.stdout != ''"
