---
# dependency:
#   name: galaxy
#   options:
#     requirements-file: collections.yml
driver:
  name: docker
lint: |
  set -e
  ansible-lint . --exclude ./.tox/ --exclude ./.git/
platforms:

  - name: ubuntu_lighthouse
    groups:
      - lighthouse
    image: ubuntu:22.04
    dockerfile: ./Dockerfile.j2
    privileged: true
    cgroupns_mode: host
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    command: /sbin/init

  - name: centos_7_lighthouse
    groups:
      - lighthouse
    image: centos:7
    dockerfile: ./Dockerfile.j2
    privileged: true
    cgroupns_mode: host
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    command: /usr/sbin/init

provisioner:
  name: ansible
verifier:
  name: ansible
